services:
  - type: web
    name: n8n
    env: docker
    dockerCommand: n8n
    dockerImage: docker.io/n8nio/n8n:latest
    region: oregon
    plan: free
    envVars:
      - key: PORT
        value: "5678"
      - key: WEBHOOK_URL
        value: https://your-n8n-app.onrender.com/
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1

databases:
  - name: n8n-db
    plan: free
